### ISSUE TITLE
can i replace the PCA data in SCimplify?

### ISSUE THREAD

**Issue by Phoenix12580** [GfellerLab/SuperCell#28]
I used 50 genset signature score  as the seurat PCA reduction to identify cell cluster 
and how to use 50 genset signature score as the PCA in SCimplify to detects metacells
Thank you for your work!

**Comment by leonardHerault** [comment]
Hi,

Thanks for your interest in SuperCell!
You should be able to do this by using your gene signatures as the input `X` matrix with the `SCimplify_from_embedding` function.

Best,

LH

**Comment by Phoenix12580** [comment]
> Hi,
> 
> Thanks for your interest in SuperCell! You should be able to do this by using your gene signatures as the input `X` matrix with the `SCimplify_from_embedding` function.
> 
> Best,
> 
> LH

Thank you very much!

**Comment by Phoenix12580** [comment]
> Hi, 嗨，
> 
> Thanks for your interest in SuperCell!感谢您对 SuperCell 的兴趣！ You should be able to do this by using your gene signatures as the input `X` matrix with the `SCimplify_from_embedding` function.您应该能够通过使用您的基因特征作为输入 `X` 矩阵，并使用 `SCimplify_from_embedding` 函数来完成此操作。
> 
> Best, Best, 最好的
> 
> LH

I did not find SCimplify_from_embedding function，where is it? Thanks a lot

**Comment by mariiabilous** [comment]
Hi @Phoenix12580,

here it is https://github.com/GfellerLab/SuperCell/blob/5de820e93ba4991b532ed2ac7ac7a09820bb0164/R/SCimplify.R#L377 
You might need to re-install SuperCell if you don't have it 

```
if (!requireNamespace("remotes")) install.packages("remotes")
remotes::install_github("GfellerLab/SuperCell")
```
Best,
Mariia

**Comment by Phoenix12580** [comment]
> Hi @Phoenix12580, 嗨，
> 
> here it is  这里就是
> 
> https://github.com/GfellerLab/SuperCell/blob/5de820e93ba4991b532ed2ac7ac7a09820bb0164/R/SCimplify.R#L377
> 
> 
> You might need to re-install SuperCell if you don't have it
> 您可能需要重新安装 SuperCell，如果您没有它
> ```
> if (!requireNamespace("remotes")) install.packages("remotes")
> remotes::install_github("GfellerLab/SuperCell")
> ```
> 
> Best, Best, 最好的 Mariia 玛丽亚

Oh， thanks a lot !  Have a nice day!~
