### ISSUE TITLE
ci: automated test run on a sampled dataset

### ISSUE THREAD

**Issue by AngryMaciek** [GfellerLab/SuperCell#8]
Hey, I've seen this research on [BC]2 lately, nice work!
I may suggest some improvements from the software engineering perspective:

Since this is a public repo unlimited minutes of [GitHub Actions](https://github.com/features/actions) for CI/CD are available.  

I see that there are already some instructions on how to test the functionality of this package on an example dataset in the _README_. It would be very nice to set up a simple GH Actions workflow which would trigger a testrun with every commit being pushed or every merge request being issued.
I would suggest to add a separate top level directory `test` and inside `input` and `output` subdirectories. The CI would then run test commands on the data in the former and compare the results against the latter.

More info on the Actions:
* https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/
* https://github.com/r-lib/actions
* https://usethis.r-lib.org/reference/github_actions.html
* https://github.com/maxheld83/ghactions

**Comment by AngryMaciek** [comment]
This test CI workflow should be executed on both linux and macOS platforms (options in the CI YAML file) which would additionally prove that installation on both platforms run smoothly :)

**Comment by mariiabilous** [comment]
Dear @AngryMaciek, 

Thanks a lot for your suggestion! It was very helpful! I learned a bit about actions and tests and find it very useful. Still lots of work to do, but the first steps are done (#16, #17).

Best, 
Mariia
